server:
  port: 9091
auth-server:
  url: ${keycloak-client.server-url}
  client: web
  token-uri: auth/realms/${keycloak-client.realm}/protocol/openid-connect/token
  cli-token-uri: auth/realms/master/protocol/openid-connect/token
  logout-uri: auth/realms/${keycloak-client.realm}/protocol/openid-connect/logout
  users-uri: auth/admin/realms/${keycloak-client.realm}/users
  grant-type: password
  test-username: ion.ionetsss@gmail.com
  test_password: test
  admin-secret: 530e9165-756c-4f2c-a9ac-5ff1c0cfd948
keycloak-client:
  server-url: https://auth-dev.agenadev.com
  realm: vet-at-home
profiles:
  url: http://localhost:8095
  profiles-url: api/v1/profiles
  profiles-me-url: api/v1/profiles/me
  pets-url: api/v1/pets
  service-url: api/v1/service/profile
  root-service-url: api/v1/service
  service-pets-url: api/v1/service/pets
  search-profiles-url: api/v1/profiles/search
api-gw:
  url: http://vet-api-dev.agenadev.com
#  url: http://localhost:8081
test:
  test-user-id: 04d89ae7-d834-4327-a769-44cfe445109b
feign.client.config.default.loggerLevel: full
logging.level:
    com.agenatech: DEBUG

